#!/bin/bash

# An easy solution would be to download whois and run
# sudo install whois

whois slash16.org

# You will find the provider is Amazon Cloudfront
# Name Server: NS-1236.AWSDNS-26.ORG
# Name Server: NS-144.AWSDNS-18.COM
# Name Server: NS-686.AWSDNS-21.NET
# Name Server: NS-1989.AWSDNS-56.CO.UK