#!/bin/bash

# Dynamic Host Configuration Protocol is an application layer protocol
# used by hosts for obtaining network setup information.
# The DHCP is controlled by a DHCP server that dynamically distributes
# network configuration parameters e.g IP address, subnet mask and
# gateway address.

 cat /var/lib/dhcp/dhclient.eth0.leases

# The IPs assigned by the DHCP server are indicated in the eth0 interface.